SELECT 
USER_MARKE, 
USER_PRODUKTART, 
USER_LENKUNG, 
USER_KATALOGUMFANG, 
USER_ISO, 
USER_REGISO, 
USER_EXPAND_BNB,
USER_SHORT_SEARCHPATH, 
USER_REQUEST_SAZ, 
USER_SHOW_PRODDATE, 
USER_SUCHRAUM, 
USER_SHOW_PREISE, 
USER_SHOW_TIPPS, 
USER_PRIMAERMARKT_ID, 
USER_TABLESTRETCH, 
USER_FONTSIZE, 
USER_DFT_VERBAUMENGE 
FROM W_USER_EINSTELLUNGEN@ETK_NUTZER 
WHERE USER_FIRMA_ID = '111' AND USER_ID = 'ADMIN'