SELECT DISTINCT
    BTZEILEN_BILDPOSNR BILDNUMMER,
    TEIL_HAUPTGR TEIL_HG,
    TEIL_UNTERGRUP TEIL_UG,
    TEIL_SACHNR TEIL_SACHNUMMER,
    TBEN.BEN_TEXT TEIL_BENENNUNG,
    TEIL_BENENNZUS TEIL_ZUSATZ, 
    TEIL_ENTFALL_KEZ TEIL_ENTFALL, 
    TEIL_TEXTCODE_KOM TEIL_KOMMENTAR_ID, 
    TKBEN.BEN_TEXT TEIL_KOMMENTAR, 
    TEIL_KOM_PI TEIL_KOMM_PI, 
    TEIL_VORHANDEN_SI TEIL_SI, 
    TEIL_IST_REACH TEIL_REACH, 
    TEIL_IST_ASPG TEIL_ASPG, 
    TEIL_IST_STECKER TEIL_STECKER, 
    SI_DOKART SI_DOKART,
    DECODE(TCP_SACHNR, TCP_SACHNR, 'C', NULL) TEIL_TC,
    NVL(TCP_PRODDAT_REL, 'N') TEIL_TC_PRODDATRELEVANT,
    GRPINFO_LEITAW_PA GRP_PA,
    GRPINFO_LEITAW_HG GRP_HG,
    GRPINFO_LEITAW_UG GRP_UG, 
    GRPINFO_LEITAW_NR GRP_LFDNR, 
    BTZEILENV_VMENGE MENGE, 
    BTZEILEN_KAT KAT_KZ, 
    BTZEILEN_AUTOMATIK GETRIEBE_KZ, 
    BTZEILEN_LENKG LENKUNG_KZ, 
    BTZEILEN_EINS EINSATZ, 
    BTZEILEN_AUSLF AUSLAUF, 
    BTZEILEN_BEDKEZ || NVL(TO_CHAR(BTZEILEN_REGELNR), '') BEDINGUNG_KZ, 
    BTZEILEN_KOMMBT KOMMBT, 
    BTZEILEN_KOMMVOR KOMMVOR, 
    BTZEILEN_KOMMNACH KOMMNACH, 
    TEIL_RUECK_PFL RUECKSENDEPFLICHT, 
    KS_SACHNR_SATZ SATZ_SACHNUMMER, 
    BTZEILEN_GRUPPEID GRUPPEID, 
    BTZEILEN_BLOCKNR BLOCKNR, 
    BNBBEN.BEN_TEXT BNBBENTEXT, 
    BTZEILEN_POS POS, 
    BTZEILENV_ALTER_KZ BTZALTER 
FROM W_BTZEILEN_VERBAUUNG 
    INNER JOIN W_BTZEILEN ON (BTZEILENV_BTNR = BTZEILEN_BTNR AND BTZEILENV_POS = BTZEILEN_POS) 
    INNER JOIN W_TEIL ON (BTZEILEN_SACHNR = TEIL_SACHNR) 
    INNER JOIN W_BEN_GK TBEN ON (TEIL_TEXTCODE = TBEN.BEN_TEXTCODE AND TBEN.BEN_ISO = 'RU' AND TBEN.BEN_REGISO = '  ') 
    LEFT JOIN W_KOMPL_SATZ ON (BTZEILEN_SACHNR = KS_SACHNR_SATZ AND KS_MARKE_TPS = 'BMW') 
    LEFT JOIN W_TC_PERFORMANCE ON (TCP_MOSPID = 53281 AND TCP_SACHNR = BTZEILEN_SACHNR  AND TCP_DATUM_VON <= 20190311 AND (TCP_DATUM_BIS IS NULL OR TCP_DATUM_BIS >= 20190311)) 
    LEFT JOIN W_GRP_INFORMATION ON (BTZEILENV_MOSPID = GRPINFO_MOSPID AND GRPINFO_SACHNR = BTZEILEN_SACHNR AND GRPINFO_TYP = '  ') 
    LEFT JOIN W_BEN_GK TKBEN ON (TEIL_TEXTCODE_KOM = TKBEN.BEN_TEXTCODE AND TKBEN.BEN_ISO = 'RU' AND TKBEN.BEN_REGISO = '  ') 
    LEFT JOIN W_SI ON (SI_SACHNR = TEIL_SACHNR) 
    LEFT JOIN W_BILDTAF_BNBBEN ON (BILDTAFB_BTNR = BTZEILENV_BTNR AND BILDTAFB_BILDPOSNR = BTZEILEN_BILDPOSNR) 
    LEFT JOIN W_BEN_GK BNBBEN ON (BILDTAFB_TEXTCODE = BNBBEN.BEN_TEXTCODE AND BNBBEN.BEN_ISO = 'RU' AND BNBBEN.BEN_REGISO = '  ') 
WHERE BTZEILENV_MOSPID = 53281 AND BTZEILENV_BTNR = '26_0240' 
ORDER BY POS, GRP_PA, GRP_HG, GRP_UG, GRP_LFDNR, SI_DOKART